# Generated by Django 3.2.25 on 2025-03-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.CharField(db_index=True, max_length=20, verbose_name='图片标识'),
        ),
    ]
