# Generated by Django 3.2.25 on 2025-03-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='视频地址')),
                ('cover', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, verbose_name='视频简介')),
                ('identifier', models.CharField(db_index=True, max_length=20, verbose_name='视频标识')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['order'],
            },
        ),
    ]
