# Generated by Django 3.2.25 on 2025-03-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='视频标题')),
                ('video_url', models.URLField(max_length=500, verbose_name='视频地址')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图地址')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('source_name', models.CharField(default='中华医学会科学普及部', max_length=255, verbose_name='来源机构')),
                ('source_url', models.URLField(unique=True, verbose_name='来源地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('identifier', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='唯一标识')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-created_at'],
            },
        ),
    ]
