# Generated by Django 3.2.25 on 2025-03-29 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source_url',
        ),
        migrations.AddField(
            model_name='video',
            name='publish_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_name',
            field=models.CharField(max_length=255, verbose_name='来源机构'),
        ),
    ]
