# Generated by Django 3.2.25 on 2025-03-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250329_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='publish_data',
            new_name='published_at',
        ),
    ]
