# Generated by Django 3.2.25 on 2025-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_publish_data_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_name',
            field=models.CharField(default='中华医学会科学普及部', max_length=255, verbose_name='来源机构'),
        ),
    ]
