# Generated by Django 3.2.25 on 2025-04-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20250330_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='image_ref',
        ),
    ]
