# Generated by Django 3.2.25 on 2025-04-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_paragraph_image_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='image_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraph_ref', to='myapp.image'),
        ),
    ]
