# Generated by Django 3.2.25 on 2025-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_paragraph_image_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=500, verbose_name='图片地址'),
        ),
    ]
